export const START_GET_BOOKS = "START_GET_BOOKS";
export const SUCCESS_GET_BOOKS = "SUCCESS_GET_BOOKS";
export const FAIL_GET_BOOKS = "FAIL_GET_BOOKS";

export const START_GET_BOOK = "START_GET_BOOK";
export const SUCCESS_GET_BOOK = "SUCCESS_GET_BOOK";
export const FAIL_GET_BOOK = "FAIL_GET_BOOK";

export const START_GET_AUTHORS = "START_GET_AUTHORS";
export const SUCCESS_GET_AUTHORS = "SUCCESS_GET_AUTHORS";
export const FAIL_GET_AUTHORS = "FAIL_GET_AUTHORS";

export const START_GET_AUTHOR = "START_GET_AUTHOR";
export const SUCCESS_GET_AUTHOR = "SUCCESS_GET_AUTHOR";
export const FAIL_GET_AUTHOR = "FAIL_GET_AUTHOR";
